# Generated by Django 4.2.4 on 2023-08-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('ANIMACAO', 'Animação'), ('AVENTURA', 'Aventura'), ('OUTROS', 'Outros'), ('AÇÃO', 'Ação'), ('PODCAST', 'Pdcast'), ('ROMANCE', 'Romance')], max_length=15),
        ),
        migrations.AlterField(
            model_name='filme',
            name='descricao',
            field=models.TextField(max_length=10000),
        ),
    ]
